name: CI/CD to AWS EC2 Instance with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./DEVOPS-FULLSTACK-PROJECT/springbootbackend
          push: true
          tags: ${{ secrets.DOCKER_USER }}/taskdockeraws-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./DEVOPS-FULLSTACK-PROJECT/reactfrontend
          push: true
          tags: ${{ secrets.DOCKER_USER }}/taskdockeraws-frontend:latest

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.AWS_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.AWS_IP }} << 'EOF'
            cd PRACTICE-DOCKER-GITACTIONS || git clone https://github.com/${{ github.repository }}.git
            cd PRACTICE-DOCKER-GITACTIONS
            git pull origin main
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d --build
          EOF
